name: google_translate_api
description: Google Translate API for Dart
version: 1.0.0
repository: https://github.com/rainerregan/google-translate-api

environment:
  sdk: ^3.3.2

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
